### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by Limpan** [Limpan/parsons-puzzle#3]
Setup docker. #1 depends on this.

**Comment by Limpan** [comment]
Fixed a basic version of this in d9205dcb98f2e101442fc45d7a0a05bd0659faec.

**Comment by Greenheart** [comment]
@Limpan Testing this right now

**Comment by Greenheart** [comment]
@Limpan After adding `.env` to the project root, it started without any problem. But does it work? :octopus:

**Comment by Limpan** [comment]
It works if you can connect to the application with your web browser. I'll document the `.env`-file.

**Comment by Greenheart** [comment]
Is this issue ready to be closed?
Also, can `feature/docker` be merged to `develop` and closed?

**Comment by Limpan** [comment]
Yep. I already merged.
